@host = http://localhost:3026
@contentType = application/json
@api_key = c9754e70-a265-4363-97c7-3b7322fe4490

### Login
# @name login
POST {{host}}/login
Content-Type: {{contentType}}
api_key: {{api_key}}

{
	"mail": "uriel.aguilera@tecmm.edu.mx",
	"pass": "pqn1fy0it9"
}

### Get me
@token = {{login.response.body.token}}

### obtener draft
GET {{host}}/convenios/draft/0001